services:
  - type: static
    name: mtg-ai-frontend
    env: static
    region: singapore
    plan: free
    buildCommand: echo "Static site - no build needed"
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
